### ISSUE TITLE
Test on Alfresco 5.0.c

### ISSUE THREAD

**Issue by softwareloop** [softwareloop/uploader-plus#65]

**Comment by tatatanja** [comment]
Hi,
i tested this module with Alfresco 5.0c and I thought everthing is ok, but then i found a curious behavior.
If i add an upload folder like /Sites/swsdp/documentLibrary/ and then view it in the repository browser and upload documents then everthing is ok. But when i go to the site's document library and upload a document, the uploader plus dialog doesn't appear.
Can I add an upload folder so that i can use the enhanced uploader in a site's document library or can i use the addon only in the repository browser?
Thanks a lot,
Tanja

**Comment by softwareloop** [comment]
Ok, it's fixed in https://github.com/softwareloop/uploader-plus/blob/a3af5bf64f8ed83d3868d39a3438ce2a3245d33f/repo-amp/src/main/amp/config/alfresco/extension/templates/webscripts/uploader-plus/allowed-content-types.get.js

**Comment by tatatanja** [comment]
Thanks a lot! It is a super AddOn!

**Comment by softwareloop** [comment]
Thanks. I'm cleaning up a few things in the code for 5.0.c and sdk 2.0.
I'm planning to make a release in the next 10 days.
